# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detectCores <- function() {
    .Call('DeepLearning_detectCores', PACKAGE = 'DeepLearning')
}

unrollDbnCpp <- function(aDBN) {
    .Call('DeepLearning_unrollDbnCpp', PACKAGE = 'DeepLearning', aDBN)
}

predictRbmCpp <- function(anRBM, aDataMatrix) {
    .Call('DeepLearning_predictRbmCpp', PACKAGE = 'DeepLearning', anRBM, aDataMatrix)
}

predictDbnCpp <- function(aDBN, aDataMatrix) {
    .Call('DeepLearning_predictDbnCpp', PACKAGE = 'DeepLearning', aDBN, aDataMatrix)
}

reconstructRbmCpp <- function(anRBM, aDataMatrix) {
    .Call('DeepLearning_reconstructRbmCpp', PACKAGE = 'DeepLearning', anRBM, aDataMatrix)
}

reconstructDbnCpp <- function(aDBN, aDataMatrix) {
    .Call('DeepLearning_reconstructDbnCpp', PACKAGE = 'DeepLearning', aDBN, aDataMatrix)
}

pretrainRbmCpp <- function(anRBM, aDataMatrix, params, diag) {
    .Call('DeepLearning_pretrainRbmCpp', PACKAGE = 'DeepLearning', anRBM, aDataMatrix, params, diag)
}

pretrainDbnCpp <- function(aDBN, aDataMatrix, params, diag, aSkip) {
    .Call('DeepLearning_pretrainDbnCpp', PACKAGE = 'DeepLearning', aDBN, aDataMatrix, params, diag, aSkip)
}

trainDbnCpp <- function(aDBN, aDataMatrix, trainParams, diag) {
    .Call('DeepLearning_trainDbnCpp', PACKAGE = 'DeepLearning', aDBN, aDataMatrix, trainParams, diag)
}

reverseRbmCpp <- function(anRBM) {
    .Call('DeepLearning_reverseRbmCpp', PACKAGE = 'DeepLearning', anRBM)
}

reverseDbnCpp <- function(aDBN) {
    .Call('DeepLearning_reverseDbnCpp', PACKAGE = 'DeepLearning', aDBN)
}

energyRbmCpp <- function(anRBM, aDataMatrix) {
    .Call('DeepLearning_energyRbmCpp', PACKAGE = 'DeepLearning', anRBM, aDataMatrix)
}

energyDbnCpp <- function(aDBN, aDataMatrix) {
    .Call('DeepLearning_energyDbnCpp', PACKAGE = 'DeepLearning', aDBN, aDataMatrix)
}

errorRbmCpp <- function(anRBM, aDataMatrix) {
    .Call('DeepLearning_errorRbmCpp', PACKAGE = 'DeepLearning', anRBM, aDataMatrix)
}

errorDbnCpp <- function(aDBN, aDataMatrix) {
    .Call('DeepLearning_errorDbnCpp', PACKAGE = 'DeepLearning', aDBN, aDataMatrix)
}

unit_DbnGradient <- function(aDBN, aDataMatrix) {
    .Call('DeepLearning_unit_DbnGradient', PACKAGE = 'DeepLearning', aDBN, aDataMatrix)
}

